/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tec.entregables;

import java.awt.Color;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Admin
 */
public class Interfaz_Main extends javax.swing.JFrame {
    private Counter miCounter;
    private Cliente miCliente;
    private Casillero miCasillero;
    private Articulo MiArticulo;
    /**
     * Creates new form JFrame_Main
     */
    public Interfaz_Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        GrupoCheckSobre = new javax.swing.ButtonGroup();
        GrupoCheckSexo = new javax.swing.ButtonGroup();
        FondoMain = new javax.swing.JDesktopPane();
        DescripcionMain = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane5 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        TextoCounterNombre = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        TextoCedulaCounter = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        SpinnerTamCounter = new javax.swing.JSpinner();
        botonCounter = new javax.swing.JButton();
        LabelBotonCrear = new javax.swing.JLabel();
        SeleccionUbicacionCounter = new javax.swing.JComboBox<>();
        PestañaClientes = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        LabelConsulta = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        txtConsulta = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        lblResConsulta = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        BotonNuevoCliente = new javax.swing.JButton();
        TextoCorreo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TextoIdCasillero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TextoTelefono = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        TextoDireccion = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CheckMasculino = new javax.swing.JCheckBox();
        CheckFemenino = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        LabelNuevoCliente = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblBotonCliente = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PestañaArticulos = new javax.swing.JPanel();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        PestañaRetiro = new javax.swing.JPanel();
        LabelRetiro = new javax.swing.JLabel();
        BotonRetiro = new javax.swing.JButton();
        TextoRetiro = new javax.swing.JTextField();
        ErrorRetiro = new javax.swing.JLabel();
        PestañaRecepcion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        SeleccionPaquete = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        SeleccionSobre = new javax.swing.JComboBox<>();
        CheckAereo = new javax.swing.JCheckBox();
        CheckManila = new javax.swing.JCheckBox();
        LabelSobre = new javax.swing.JLabel();
        LabelPaquete = new javax.swing.JLabel();
        SpinnerPaquetePeso = new javax.swing.JSpinner();
        CheckElectronico = new javax.swing.JCheckBox();
        CheckFragil = new javax.swing.JCheckBox();
        LabelRevista = new javax.swing.JLabel();
        LabelPeso = new javax.swing.JLabel();
        BotonComprobarArticulos = new javax.swing.JButton();
        LabelErrorPaquete = new javax.swing.JLabel();
        SeleccionRevista = new javax.swing.JComboBox<>();
        CheckCatalogo = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Casilleros");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(250, 100));
        setResizable(false);

        DescripcionMain.setBackground(new java.awt.Color(255, 255, 255));
        DescripcionMain.setFont(new java.awt.Font("Yu Gothic Medium", 1, 12)); // NOI18N
        DescripcionMain.setForeground(new java.awt.Color(255, 255, 255));
        DescripcionMain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        DescripcionMain.setText("Bienvenido, Seleccione la pestaña con la accion que desea realizar");
        DescripcionMain.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DescripcionMain.setName("DescripcionMain"); // NOI18N

        jTabbedPane5.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel8.setText("Nombre del Counter:");

        jLabel13.setText("Cedula Juridica");

        jLabel14.setText("Ubicacion:");

        TextoCedulaCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCedulaCounterActionPerformed(evt);
            }
        });

        jLabel15.setText("Tamaño del Counter:");

        SpinnerTamCounter.setModel(new javax.swing.SpinnerNumberModel(1, 1, 50, 1));
        SpinnerTamCounter.setToolTipText("");
        SpinnerTamCounter.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        botonCounter.setText("Crear");
        botonCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCounterActionPerformed(evt);
            }
        });

        SeleccionUbicacionCounter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "San Jose", "Alajuela", "Cartago" }));
        SeleccionUbicacionCounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionUbicacionCounterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SpinnerTamCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoCounterNombre)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoCedulaCounter, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGroup(jPanel11Layout.createSequentialGroup()
                            .addComponent(botonCounter)
                            .addGap(65, 65, 65)
                            .addComponent(LabelBotonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(SeleccionUbicacionCounter, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(729, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoCounterNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoCedulaCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SeleccionUbicacionCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SpinnerTamCounter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonCounter)
                    .addComponent(LabelBotonCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jTabbedPane5.addTab("Crear", jPanel11);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jTabbedPane5)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Counter", jPanel5);

        jTabbedPane3.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLabel16.setText("Consultar Disponibilidad de casillero");

        jLabel17.setText("Numero de casillero:");

        LabelConsulta.setText(" ");

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        txtConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtConsulta))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                        .addComponent(btnConsultar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(lblResConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblResConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtConsulta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelConsulta))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnConsultar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Consultar", jPanel14);

        jLabel5.setText("Nombre:");

        TextoNombre.setText(" ");
        TextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreActionPerformed(evt);
            }
        });

        BotonNuevoCliente.setText("Agregar");
        BotonNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonNuevoClienteActionPerformed(evt);
            }
        });

        TextoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCorreoActionPerformed(evt);
            }
        });

        jLabel6.setText("Correo:");

        jLabel7.setText("Id del Casillero");

        TextoIdCasillero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoIdCasilleroActionPerformed(evt);
            }
        });

        jLabel9.setText("Telefono:");

        TextoTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoTelefonoActionPerformed(evt);
            }
        });

        jLabel10.setText("Direccion:");

        TextoDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoDireccionActionPerformed(evt);
            }
        });

        jLabel11.setText("Sexo:");

        GrupoCheckSexo.add(CheckMasculino);
        CheckMasculino.setText("Masculino");
        CheckMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckMasculinoActionPerformed(evt);
            }
        });

        GrupoCheckSexo.add(CheckFemenino);
        CheckFemenino.setText("Femenino");

        jLabel12.setText("Fecha de Nacimiento:");

        LabelNuevoCliente.setText(" ");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                                .addComponent(CheckMasculino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CheckFemenino))
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel5)
                                        .addComponent(TextoNombre)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel7)
                                        .addComponent(TextoIdCasillero)
                                        .addComponent(TextoCorreo)
                                        .addComponent(jLabel9)
                                        .addComponent(TextoTelefono, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                                    .addComponent(TextoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel13Layout.createSequentialGroup()
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BotonNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184)
                                .addComponent(lblBotonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoIdCasillero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextoDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckMasculino)
                    .addComponent(CheckFemenino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BotonNuevoCliente)
                        .addComponent(LabelNuevoCliente)
                        .addComponent(lblBotonCliente))
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Nuevo", jPanel13);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel19.setText("Borrar Cliente");

        jLabel20.setText("Inserte el id de Cliente");

        jButton2.setText("Borrar");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Borrar", jPanel15);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Modificar", jPanel1);

        javax.swing.GroupLayout PestañaClientesLayout = new javax.swing.GroupLayout(PestañaClientes);
        PestañaClientes.setLayout(PestañaClientesLayout);
        PestañaClientesLayout.setHorizontalGroup(
            PestañaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PestañaClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        PestañaClientesLayout.setVerticalGroup(
            PestañaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PestañaClientesLayout.createSequentialGroup()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Clientes", PestañaClientes);

        jTabbedPane4.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        LabelRetiro.setText("Introduzca su identificador de cliente");

        BotonRetiro.setText("Consultar");
        BotonRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRetiroActionPerformed(evt);
            }
        });

        TextoRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoRetiroActionPerformed(evt);
            }
        });

        ErrorRetiro.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout PestañaRetiroLayout = new javax.swing.GroupLayout(PestañaRetiro);
        PestañaRetiro.setLayout(PestañaRetiroLayout);
        PestañaRetiroLayout.setHorizontalGroup(
            PestañaRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PestañaRetiroLayout.createSequentialGroup()
                .addGroup(PestañaRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PestañaRetiroLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(PestañaRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoRetiro))
                        .addGap(76, 76, 76)
                        .addComponent(ErrorRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PestañaRetiroLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(BotonRetiro)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PestañaRetiroLayout.setVerticalGroup(
            PestañaRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PestañaRetiroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(PestañaRetiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PestañaRetiroLayout.createSequentialGroup()
                        .addComponent(LabelRetiro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextoRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ErrorRetiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotonRetiro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Retiro", PestañaRetiro);

        jLabel3.setText("Seleccione:");

        SeleccionPaquete.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sobre", "Paquete", "Revista" }));
        SeleccionPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionPaqueteActionPerformed(evt);
            }
        });

        jLabel2.setText(" Tipo de articulo");

        SeleccionSobre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Documento", "Articulo Pequeño" }));
        SeleccionSobre.setEnabled(false);
        SeleccionSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionSobreActionPerformed(evt);
            }
        });

        GrupoCheckSobre.add(CheckAereo);
        CheckAereo.setText("Aéreo");
        CheckAereo.setEnabled(false);
        CheckAereo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckAereoActionPerformed(evt);
            }
        });

        GrupoCheckSobre.add(CheckManila);
        CheckManila.setText("Manila");
        CheckManila.setEnabled(false);
        CheckManila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckManilaActionPerformed(evt);
            }
        });

        LabelSobre.setText("Para Sobres: ");
        LabelSobre.setEnabled(false);

        LabelPaquete.setText("Para Paquetes: ");
        LabelPaquete.setEnabled(false);

        SpinnerPaquetePeso.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        SpinnerPaquetePeso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        SpinnerPaquetePeso.setEnabled(false);

        CheckElectronico.setText("Electronico");
        CheckElectronico.setEnabled(false);

        CheckFragil.setText("Fragil");
        CheckFragil.setEnabled(false);

        LabelRevista.setText("Para Revistas:");
        LabelRevista.setEnabled(false);

        LabelPeso.setText("Peso:");
        LabelPeso.setEnabled(false);

        BotonComprobarArticulos.setText("Comprobar");
        BotonComprobarArticulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonComprobarArticulosActionPerformed(evt);
            }
        });

        LabelErrorPaquete.setText(" ");
        LabelErrorPaquete.setEnabled(false);

        SeleccionRevista.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Negocios", "Moda/Belleza", "Tecnología", "Salud/Medicina", "Cocina", "Otro" }));
        SeleccionRevista.setEnabled(false);

        CheckCatalogo.setText("De Catalogo");
        CheckCatalogo.setEnabled(false);
        CheckCatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckCatalogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PestañaRecepcionLayout = new javax.swing.GroupLayout(PestañaRecepcion);
        PestañaRecepcion.setLayout(PestañaRecepcionLayout);
        PestañaRecepcionLayout.setHorizontalGroup(
            PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PestañaRecepcionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PestañaRecepcionLayout.createSequentialGroup()
                        .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PestañaRecepcionLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel3))
                            .addGroup(PestañaRecepcionLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(SeleccionPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(PestañaRecepcionLayout.createSequentialGroup()
                        .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PestañaRecepcionLayout.createSequentialGroup()
                                .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelSobre)
                                    .addGroup(PestañaRecepcionLayout.createSequentialGroup()
                                        .addComponent(CheckAereo)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(CheckManila))
                                    .addComponent(SeleccionSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PestañaRecepcionLayout.createSequentialGroup()
                                            .addGap(120, 120, 120)
                                            .addComponent(LabelPaquete))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PestañaRecepcionLayout.createSequentialGroup()
                                            .addComponent(LabelPeso)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(SpinnerPaquetePeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PestañaRecepcionLayout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addComponent(CheckElectronico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(CheckFragil)))
                                .addGap(44, 44, 44)
                                .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CheckCatalogo)
                                    .addComponent(LabelRevista)
                                    .addComponent(SeleccionRevista, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PestañaRecepcionLayout.createSequentialGroup()
                                .addComponent(BotonComprobarArticulos)
                                .addGap(18, 18, 18)
                                .addComponent(LabelErrorPaquete)))
                        .addGap(0, 402, Short.MAX_VALUE))))
        );
        PestañaRecepcionLayout.setVerticalGroup(
            PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PestañaRecepcionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(SeleccionPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSobre)
                    .addComponent(LabelPaquete)
                    .addComponent(LabelRevista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SeleccionSobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SpinnerPaquetePeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelPeso)
                    .addComponent(SeleccionRevista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CheckAereo)
                    .addComponent(CheckManila)
                    .addComponent(CheckElectronico)
                    .addComponent(CheckFragil)
                    .addComponent(CheckCatalogo))
                .addGap(18, 18, 18)
                .addGroup(PestañaRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonComprobarArticulos)
                    .addComponent(LabelErrorPaquete))
                .addContainerGap(288, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Recepcion", PestañaRecepcion);

        jLabel21.setText("Consultar por medio de Email");

        jLabel22.setText("Insertar eMail:");

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton3.setText("Enviar Mail");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel22)
                        .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField6)))
                .addContainerGap(804, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addContainerGap(347, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Consulta", jPanel2);

        javax.swing.GroupLayout PestañaArticulosLayout = new javax.swing.GroupLayout(PestañaArticulos);
        PestañaArticulos.setLayout(PestañaArticulosLayout);
        PestañaArticulosLayout.setHorizontalGroup(
            PestañaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PestañaArticulosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );
        PestañaArticulosLayout.setVerticalGroup(
            PestañaArticulosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PestañaArticulosLayout.createSequentialGroup()
                .addComponent(jTabbedPane4)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Artículos", PestañaArticulos);

        jLabel1.setFont(new java.awt.Font("Felix Titling", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Mantenimiento de Casilleros");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setOpaque(true);

        FondoMain.setLayer(DescripcionMain, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoMain.setLayer(jTabbedPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        FondoMain.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout FondoMainLayout = new javax.swing.GroupLayout(FondoMain);
        FondoMain.setLayout(FondoMainLayout);
        FondoMainLayout.setHorizontalGroup(
            FondoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FondoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addGroup(FondoMainLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(FondoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoMainLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(411, 411, 411))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FondoMainLayout.createSequentialGroup()
                                .addComponent(DescripcionMain)
                                .addGap(352, 352, 352)))))
                .addContainerGap())
        );
        FondoMainLayout.setVerticalGroup(
            FondoMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FondoMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DescripcionMain, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        DescripcionMain.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FondoMain)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FondoMain)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeleccionPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionPaqueteActionPerformed
        // TODO add your handling code here:
        int TipoPaquete;
        TipoPaquete = SeleccionPaquete.getSelectedIndex();
        if (TipoPaquete == 0){
            CheckAereo.setEnabled(true);
            CheckManila.setEnabled(true);
            SeleccionSobre.setEnabled(true);
            LabelSobre.setEnabled(true);
            
            SeleccionRevista.setEnabled(false);
            LabelPaquete.setEnabled(false);
            SpinnerPaquetePeso.setEnabled(false);
            CheckElectronico.setEnabled(false);
            CheckFragil.setEnabled(false);
            CheckCatalogo.setEnabled(false);
            LabelPeso.setEnabled(false);
            LabelRevista.setEnabled(false);
        }else if (TipoPaquete == 1){
            LabelPaquete.setEnabled(true);
            SpinnerPaquetePeso.setEnabled(true);
            CheckElectronico.setEnabled(true);
            CheckFragil.setEnabled(true);
            LabelPeso.setEnabled(true);
            
            CheckCatalogo.setEnabled(false);
            SeleccionRevista.setEnabled(false);
            LabelSobre.setEnabled(false);
            CheckAereo.setEnabled(false);
            CheckManila.setEnabled(false);
            SeleccionSobre.setEnabled(false);
            LabelRevista.setEnabled(false);
        }else if (TipoPaquete == 2){
            LabelRevista.setEnabled(true);
            SeleccionRevista.setEnabled(true);
            CheckCatalogo.setEnabled(true);
            
            LabelSobre.setEnabled(false);
            CheckAereo.setEnabled(false);
            CheckManila.setEnabled(false);
            SeleccionSobre.setEnabled(false);
            LabelPaquete.setEnabled(false);
            SpinnerPaquetePeso.setEnabled(false);
            CheckElectronico.setEnabled(false);
            CheckFragil.setEnabled(false);
            LabelPeso.setEnabled(false);
        }
    }//GEN-LAST:event_SeleccionPaqueteActionPerformed

    private void TextoRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoRetiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoRetiroActionPerformed

    private void BotonRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRetiroActionPerformed
        ErrorRetiro.setText("Error");
        ErrorRetiro.setForeground(Color.red);
    }//GEN-LAST:event_BotonRetiroActionPerformed

    private void SeleccionSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionSobreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionSobreActionPerformed

    private void CheckManilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckManilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckManilaActionPerformed

    private void CheckAereoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckAereoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckAereoActionPerformed

    private void BotonComprobarArticulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonComprobarArticulosActionPerformed
        int TipoPaquete;
        boolean correcto0 = true;
        boolean correcto1 = true;
        boolean correcto2 = true;
        
        TipoPaquete = SeleccionPaquete.getSelectedIndex();
        if (TipoPaquete == 0){
            if (SeleccionSobre.getSelectedIndex()!=(0|1)){
                LabelErrorPaquete.setForeground(Color.red);
                LabelErrorPaquete.setText("Error: Faltan Datos");
                LabelErrorPaquete.setEnabled(true);
            }
            if (correcto0){
//                MiArticulo = new Articulo("Sobre", 2222, "Sobre", String remitente, double peso);
//                agregarArticuloPendiente(Counter miCounter, Articulo articulo, String estadoArticulo);
            }
        } else if (TipoPaquete == 1){
            
        } else if (TipoPaquete == 2){
            
        } else {
            LabelErrorPaquete.setForeground(Color.red);
            LabelErrorPaquete.setText("Error: Seleccione el tipo");
            LabelErrorPaquete.setEnabled(true);
        }
    }//GEN-LAST:event_BotonComprobarArticulosActionPerformed

    private void TextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoNombreActionPerformed

    private void TextoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCorreoActionPerformed

    private void TextoTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoTelefonoActionPerformed

    private void TextoDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDireccionActionPerformed

    private void BotonNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonNuevoClienteActionPerformed
        // TODO add your handling code here:
        lblBotonCliente.setText("");
        String telefono = TextoTelefono.getText();
        String correo = TextoCorreo.getText();
        if (!Validaciones.validarTelefono(telefono) || !Validaciones.validarCorreo(correo)) {
            lblBotonCliente.setText("Hay un error en el correo o telefono");
        }
        int stoiID = Integer.parseInt(TextoIdCasillero.getText());
        miCasillero = new Casillero(123,"hola");
        try{
//            miCounter.registrarCliente(TextoNombre.getText(),stoiID, TextoTelefono.getText()
//            , TextoCorreo.getText(), CheckFemenino.isSelected(), miCasillero, "2");
            lblBotonCliente.setText("Agregado Correctamente");
        } catch(Exception e) {
          
          lblBotonCliente.setText(e.getMessage());
          System.out.println(e.getMessage());
          
        }   
    }//GEN-LAST:event_BotonNuevoClienteActionPerformed

    private void TextoIdCasilleroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoIdCasilleroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoIdCasilleroActionPerformed

    private void CheckCatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckCatalogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckCatalogoActionPerformed

    private void TextoCedulaCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCedulaCounterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCedulaCounterActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void txtConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConsultaActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
        lblResConsulta.setText("");
        String casilleroConsulta = txtConsulta.getText();
    
        try {
            //int numeroCasillero = Integer.parseInt(casilleroConsulta);
            //String resultado = miCasillero.getEstado(numeroCasillero);

            //if (resultado.contains("Libre")) {
            //    lblResConsulta.setText("El casillero está libre.");
            //} else {
            //    //lblResConsulta.setText(resultado);
            //}

        } catch (NumberFormatException e) {
            lblResConsulta.setText("Por favor, introduce un número válido.");
        }
        
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void botonCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCounterActionPerformed
        // TODO add your handling code here:
        String nombreCounter = TextoCounterNombre.getText();
        String Ubicacion = "";
        int SelUbi = SeleccionUbicacionCounter.getSelectedIndex();

        if (SelUbi == 0){
            Ubicacion = "San Jose";
        } else if (SelUbi == 1){
            Ubicacion = "Alajuela";
        } else if (SelUbi == 2){
            Ubicacion = "Cartago";
        }

        int cantCasilleros = (int)SpinnerTamCounter.getValue();
        String Cedula = TextoCedulaCounter.getText();

        if (Validaciones.validarCedula(Cedula)){
            miCounter = new Counter(nombreCounter, Ubicacion, cantCasilleros, Cedula);
            LabelBotonCrear.setText("Counter Creado Correctamente");
        } else {
            LabelBotonCrear.setText("Datos Invalidos");
        }
    }//GEN-LAST:event_botonCounterActionPerformed

    private void SeleccionUbicacionCounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionUbicacionCounterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeleccionUbicacionCounterActionPerformed

    private void CheckMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckMasculinoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz_Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonComprobarArticulos;
    private javax.swing.JButton BotonNuevoCliente;
    private javax.swing.JButton BotonRetiro;
    private javax.swing.JCheckBox CheckAereo;
    private javax.swing.JCheckBox CheckCatalogo;
    private javax.swing.JCheckBox CheckElectronico;
    private javax.swing.JCheckBox CheckFemenino;
    private javax.swing.JCheckBox CheckFragil;
    private javax.swing.JCheckBox CheckManila;
    private javax.swing.JCheckBox CheckMasculino;
    private javax.swing.JLabel DescripcionMain;
    private javax.swing.JLabel ErrorRetiro;
    private javax.swing.JDesktopPane FondoMain;
    private javax.swing.ButtonGroup GrupoCheckSexo;
    private javax.swing.ButtonGroup GrupoCheckSobre;
    private javax.swing.JLabel LabelBotonCrear;
    private javax.swing.JLabel LabelConsulta;
    private javax.swing.JLabel LabelErrorPaquete;
    private javax.swing.JLabel LabelNuevoCliente;
    private javax.swing.JLabel LabelPaquete;
    private javax.swing.JLabel LabelPeso;
    private javax.swing.JLabel LabelRetiro;
    private javax.swing.JLabel LabelRevista;
    private javax.swing.JLabel LabelSobre;
    private javax.swing.JPanel PestañaArticulos;
    private javax.swing.JPanel PestañaClientes;
    private javax.swing.JPanel PestañaRecepcion;
    private javax.swing.JPanel PestañaRetiro;
    private javax.swing.JComboBox<String> SeleccionPaquete;
    private javax.swing.JComboBox<String> SeleccionRevista;
    private javax.swing.JComboBox<String> SeleccionSobre;
    private javax.swing.JComboBox<String> SeleccionUbicacionCounter;
    private javax.swing.JSpinner SpinnerPaquetePeso;
    private javax.swing.JSpinner SpinnerTamCounter;
    private javax.swing.JTextField TextoCedulaCounter;
    private javax.swing.JTextField TextoCorreo;
    private javax.swing.JTextField TextoCounterNombre;
    private javax.swing.JTextField TextoDireccion;
    private javax.swing.JTextField TextoIdCasillero;
    private javax.swing.JTextField TextoNombre;
    private javax.swing.JTextField TextoRetiro;
    private javax.swing.JTextField TextoTelefono;
    private javax.swing.JButton botonCounter;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTabbedPane jTabbedPane5;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblBotonCliente;
    private javax.swing.JLabel lblResConsulta;
    private javax.swing.JTextField txtConsulta;
    // End of variables declaration//GEN-END:variables
}
